services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
      - USER=$AUTH_USER
      - PASS=$AUTH_PASSWORD
    volumes:
      - ./config:/config
      - "$DOWNLOADS_DIR:/downloads"
      - ./watch:/watch
      - ./bin:/custom/bin
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
