services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
      - USER=$USER
      - PASS=$PASSWORD
    volumes:
      - ./config:/config
      - "$DOWNLOADS_DIR:/downloads"
      - ./watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
